### ISSUE TITLE
Question about -include option

### ISSUE THREAD

**Issue by bsun312** [arcadesdude/BRU#10]
Hello,

I'm trying to uninstall all office 365 apps as well as all apps with "Dell" in the name. I am using the below command but im not sure im getting the expressions correct...

`Bloatware-Removal-Utility.ps1 -silent -nd -nr -include '"365\ .*|Dell\ .*"'`

Could you let me know what my -include should look like ?

Thanks.

**Comment by arcadesdude** [comment]
The \  (backslash space) is targeting a space there. You can take it out. 

`-include '"365.*|Dell.*"'`

When you use the above does it find what you want? You can also add -dr to the command to not actually remove anything so you can tweak your regular expression.

**Comment by bsun312** [comment]
That does exactly what I needed. Thank you. The backslash makes sense. What does the "." (period) do ?

**Comment by arcadesdude** [comment]
Great! The . in regular expressions means any single character including whitespace.
If you put a * after a . in a regular expression like .* it means any any characters including whitespace zero or more times. The * means zero or more of the preceding '.' (any char).
