### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jasonlshelton** [arcadesdude/BRU#13]
I'm sorry if this is not the correct way to request this.

Would it be possible to export the list of selected apps from the GUI then use the resulting file as input for a command line execution? We have 2 or 3 laptop types (some HP some Dell, etc) and want to have a script for each to kill all the OEM stuff.  It would be really useful if we could run this on a laptop, select all of the things we want removed, then export that for repeated use on identical laptops. Having the GUI is really helpful for finding everything to remove.

**Comment by arcadesdude** [comment]
Looks possible. I'm working on this now. Once a test is ready I'll ask for your feedback on it before releasing it.

By the way, if you have logs (c:\BRU) that show items that should be detected/selected by default but aren't please send logs over and I can update the default selection list or you can do a pull request if you're git-fluent :D

**Comment by arcadesdude** [comment]
There's a test build up on the dev branch with your feature request added:

https://github.com/arcadesdude/BRU/tree/dev

Please try it out and let me know if any issues (logs please in that case).

Thanks!

**Comment by jasonlshelton** [comment]
This is beyond awesome for a one person github project. Thank you so much for your work here, it's saving us a ton of effort. 

We're testing the new features and so far there have been no problems. 

Thank you.

**Comment by arcadesdude** [comment]
Great! Thanks for the feedback. The idea is no matter what brand that BRU should by default suggest/select/remove the OEM bloatware. Do you have logs from when it is run with default options silently where it is not picking up bloatware?

**Comment by arcadesdude** [comment]
My testing was also successful. I may have also fixed the 'terminating errors' showing when a UWP app was already removed. 

New release is up [https://github.com/arcadesdude/BRU/releases/tag/05-20-2021](05-20-2021).
