### ISSUE TITLE
Request for Import As Well As Export

### ISSUE THREAD

**Issue by jsadecki1** [arcadesdude/BRU#14]
Also sorry if this isnt the right place for a request but i like the gui but would love to have an import option for my exported file, is that not possible, seems only logical to me

**Comment by arcadesdude** [comment]
Please describe how you would use an import feature and why in as much detail as possible.

**Comment by jsadecki1** [comment]
hi, yes i specifically made this account to request that if we had an import selection option above the export selection option to import the file it creates, then that would then make this the perfect program for all my windows bloatware uninstalls :D

like if you just clicked import selection file then select the file that we exported using the export option, then we don't have top use the silent mode as i personally cannot for the life of me manage to get the silent mode custom selection to work

**Comment by jsadecki1** [comment]
also thanks for the brilliantly quick reply

**Comment by arcadesdude** [comment]
What issues are you having with the silent mode?

**Comment by jsadecki1** [comment]
cant work out how to put it in silent mode and how to make it so that it uses my custom selection file that i exported basically, any help would be greatly appreciated, I've went over the instructions about 7 times and cant seem to work it out

**Comment by arcadesdude** [comment]
What command line did you try for silent mode and can you post the logs?

**Comment by jsadecki1** [comment]
Sorry if im being difficult here im a total novice i dont even know where to put command lines or how to open this in silent mode

**Comment by jsadecki1** [comment]
https://www.linkpicture.com/q/Screenshot-2021-07-30-132204.png
https://www.linkpicture.com/q/Screenshot-2021-07-30-132229.png

**Comment by arcadesdude** [comment]
You'd open a command prompt in administrator mode.

**Comment by arcadesdude** [comment]
Open administrator command prompt and type
powershell

or open an administrator powershell directly like you did in the images.

Then find out where are you running the BRU from?

you'd need to do
cd c:\[path to BRU]

do that first

then your command would be

& .\Bloatware-Removal-Utility.ps1 -s -includefile
c:\BRU\BRU-Saved-Selection.xml

if "c:\BRU\BRU-Saved-Selection.xml" is where your file is

**Comment by jsadecki1** [comment]
https://www.linkpicture.com/q/Screenshot-2021-07-30-135919.png
https://www.linkpicture.com/q/Screenshot-2021-07-30-135931.png

definetly thats where its stored, should i have the contents or the folder of BSU-master in C:\BRU or something?

again thank you for dealing with such a novice :)

**Comment by arcadesdude** [comment]
Making progress...

First find where the file Bloatware-Removal-Utility.ps1 is
Then you cd to that file
so if that file is here
C:\Users\[USERNAME]\Downloads\BRU-05-20-2021\BRU-05-20-2021

then you'd replace the [USERNAME] above with your actual username
and
cd C:\Users\[USERNAME]\Downloads\BRU-05-20-2021\BRU-05-20-2021

then run the command again
& .\Bloatware-Removal-Utility.ps1 -s -includefile
c:\BRU\BRU-Saved-Selection.xml

**Comment by jsadecki1** [comment]
https://www.linkpicture.com/q/Screenshot-2021-07-30-154803.png

honestly really trying everything i can before i ask for more help here lol, there something im doing wrong?

bru folder on desktop and the export file is in bsu folder in c drive

**Comment by arcadesdude** [comment]
There's a line break in there before your exported file name which is causing it to fail. You have to get rid of that. 
Try typing it manually and not copy and pasting.
then run the command again
`& .\Bloatware-Removal-Utility.ps1 -s -includefile c:\BRU\BRU-Saved-Selection.xml`

**Comment by jsadecki1** [comment]
Brilliant, finally got it, thank you so much for your help,
all my bloatware uninstalling needs are now met 🗡️ 
have a nice day :D:D

**Comment by arcadesdude** [comment]
Great! Glad to hear!
