### ISSUE TITLE
Wasp.dll links no longer work

### ISSUE THREAD

**Issue by DrQuack32** [arcadesdude/BRU#15]
Hello

The links to wasp.dll no longer work. Any idea where this can be found?

**Comment by arcadesdude** [comment]
Looks like someone saved them here:
https://github.com/mavaddat/wasp/tree/master/Builds/Release
I'll have to update the readme/instructions sometime. Thanks for the heads
up!

**Comment by arcadesdude** [comment]
There's also this:

https://www.powershellgallery.com/packages/Wasp/2.5.0.0

**Comment by DrQuack32** [comment]
Just download the raw nupkg file and rename?
![2021-11-17 12_51_41-PowerShell Gallery _ Wasp 2 5 0 0 and 1 more page - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/72686602/142084461-d5746af3-e016-49c5-b248-a6f0b096481e.jpg)

**Comment by arcadesdude** [comment]
I haven't used that specific version but nupkg are just zips. Inside is a
couple of dll files. I don't know if renaming them will work. The first
link I sent you has a wasp.dll you can download that may work.

**Comment by arcadesdude** [comment]
OK So those versions above are quite different from the old version of WASP.dll used in my script. I've found the version needed is still hosted on archive.org from the last copy available from codeplex.com. I'll create a new release of BRU updated in the script and the readme for getting that file. 

The direct download link to the archived copy is https://web.archive.org/web/20210701003323/https://codeplexarchive.blob.core.windows.net/archive/projects/WASP/WASP.zip
