### ISSUE TITLE
Script not working in Windows Configuration Designer 

### ISSUE THREAD

**Issue by aamolshirke** [arcadesdude/BRU#16]
Hi, I am using bloatware script in the WCD provision package with -Silent parameter. It removes the HP applications but after removal of the application, it goes into OOBE mode again. log file is attached for your reference. Your response would be highly appreciate. 

[Bloatware-Removal-07-May-2022-12-19.log](https://github.com/arcadesdude/BRU/files/8667524/Bloatware-Removal-07-May-2022-12-19.log)

**Comment by aamolshirke** [comment]
Hi, I am trying to run **powershell.exe -executionpolicy Bypass -File "C:\temp\BRU-master\Bloatware-Removal-Utility.ps1" -Silent -exclude "Microsoft\ Office","Microsoft\.Office" -skiprestorepoint** still same issue

**Comment by arcadesdude** [comment]
Hi Aamolshirke,

BRU isn't intended to be run as system during OOBE inside WCD. It needs an
interactive used session even when running silently if there are any GUI
only uninstallers that need to use WASP to uninstall. Having said that, it
may work fine to uninstall applications but you'd want to disable the
options that modify HKCU as running as system (or defaultuser0) won't
affect anything (except where the default hive is loaded).

It is also not intended to skip OOBE, that is up to your configuration of
your ppkg file. Can you post a video of what is happening that you don't
want to happen? I might be able to see what is going on and fix it from
that and the logs you sent.

My recommendation and how I run BRU is to have a script that runs from the
WCD and copies the files to a folder on the c drive and sets up autologon
in the registry and set up a run key under that local admin user that you
set to autologon. The run key would launch BRU from there and you can then
delete the auto logon at the end of the process.

Thanks,

**Comment by arcadesdude** [comment]
I see you from your log you didn't have the office uninstall helper in the
folder so the office uninstall wasn't able to proceed from your previous
log. If you specifically exclude office it won't attempt to uninstall it at
all. Please provide a video about what happens that you don't want to
happen and I can look into it. Thanks.

**Comment by aamolshirke** [comment]
Hi, Thank you for your valuable response. I will create a video as earliest.

**Comment by arcadesdude** [comment]
Did you figure it out or make a video of the issue?

**Comment by arcadesdude** [comment]
Closing due to no response.
