### ISSUE TITLE
MCPR extracts to a random folder in temp

### ISSUE THREAD

**Issue by gointern** [arcadesdude/BRU#17]
A long time has passed by. Tried MCPR McAfee uninstall. It does not extract to temp/MCPR rather to a random folder for example C:\Users\username\AppData\Local\Temp\nsj20C5.tmp

**Comment by arcadesdude** [comment]
The behavior you've mentioned I've confirmed happens in the latest MCPR tool. I'll look into pushing a fix in about 2 weeks. Thanks!

**Comment by arcadesdude** [comment]
@gointern just wanted to let you know I'm still working on this. The folder it is running from I've fixed and that's the easy part. Will have more updates soon. McAfee has made many under the hood changes to their MCPR so I'm finding ways to run it silently again to skip the CAPTCHA. Taking a bit longer than I thought.

**Comment by arcadesdude** [comment]
You can try this file in the meantime. I think they're signing something now and requiring a long string to be passed to mccleanup.exe to get it to run. The latest MCPR also doesn't run on Win7 anymore so save your old MCPR.exe if you need it for that.

Possible fix to run latest MCRP (8/13/2022) silently:
https://github.com/arcadesdude/BRU/blob/c1ffbe8d1c3ada58d43583d55f0450220be5e367/Bloatware-Removal-Utility.ps1

**Comment by arcadesdude** [comment]
I've verified the linked file above works with MCPR version 10.4.194.0
Can you test?

**Comment by arcadesdude** [comment]
I've done a bit more testing and changed it so if there are new version we can add new keys which are needed to get MCPR to run silently again. Fixed in https://github.com/arcadesdude/BRU/releases/tag/08-17-2022
