### ISSUE TITLE
Only works for current user

### ISSUE THREAD

**Issue by jjacobs33589** [arcadesdude/BRU#21]
This works great but only works for the current user. If I create a new user on my computer all of the apps (disney+, Instagram, etc)  are back. Can you make so they are gone permanently?

**Comment by arcadesdude** [comment]
The app does remove provisioned packages for new users but Windows updates will reinstall those. This is just how MS does it. They really want to market their apps that nobody wants. Run it again after feature updates.

**Comment by jjacobs33589** [comment]
It doesn't seem to be doing that on mine. It also doesn't remove the apps for other existing users. Just the current one. 
Is there a step I'm missing?

**Comment by jjacobs33589** [comment]
I'm wondering too. Windows 11 comes with links to Tiktok, Disney+, Instagram, Prime Video, Spotify, and more inside of the start menu. Right when you get in. They're not actual applications but when you click on them they are downloaded even if I use this tool to remove the Microsoft Store. Is there a way to get rid of the links too so that applications can't be downloaded?

**Comment by arcadesdude** [comment]
The app is not designed to remove w10 apps from existing users other than the current user. It will remove provisioned apps that would have been installed when a new user logs in. It is designed to be for clearing bloatware on a new computer not for clearing all existing user profiles. 

The other caveat is, if a feature update (windows update) reinstalls all the provisioned packages then you'll need to run the app again to remove them or new users will get those provisioned apps installed.

**Comment by arcadesdude** [comment]
To get rid of the links you can create a blank start menu layout and have it apply to all new users but not the current user or existing users. 

https://stackoverflow.com/questions/60594329/how-to-set-a-windows-start-menu-layout-via-powershell-for-the-current-user-on-wi

https://blog.ironmansoftware.com/powershell-windows-11-start-menu/
