### ISSUE TITLE
Nothing Happens after pressing Y

### ISSUE THREAD

**Issue by rsmithghv** [arcadesdude/BRU#23]
Hi,

Any suggestions?  I am opening the .bat file as admin.  Leaving the defaults selected and ticking off a couple of other apps, press the button to uninstall.
It lists about 20 apps to uninstall, then when I press Y nothing happens.  Waited about 30 minutes, then stopped it, checked the log and it shows nothing happening either.

Tried running without creating a system restore point, and also set the execution policy in PowerShell.

This is Windows 11 PRO 21H2 on a Dell Latitude 7390 with a fresh Windows install.

Thanks,

Ralph

**Comment by arcadesdude** [comment]
Did you click in the Powershell window and accidentally go into quick edit mode? If you did it would show 'Select' at the top title bar of the Powershell window before Administrator. Just click the title bar then press space bar to resume the script if that was the case.

I've also seen it, on some very very slow systems that have hundreds of programs or have spinning platter HDDs that it takes a while to enumerate the program list. It might be getting hung up there. Fresh Windows install shouldn't do that.

My next guess and I've seen it where preinstalled AV from the manufacturer (*cough* HP *cough*) stopped the script from running. Maybe Dell SupportAssist (with its built in AV) is stopping the script from running? Or some other installed AV?

In any case, please send me the logs from the attempts and we can look into this further.

**Comment by rsmithghv** [comment]
So the good news is since I messaged you I upgraded Windows 11 on that laptop from 21H2 to 22H2.  When I ran BRU again, this time it worked as expected.

I don't know why it didn't work before, none of the possibilities you mentioned were the case - it had been a fresh Windows install, no preinstalled Dell AV or Dell tools, just Defender.

Thanks for responding to my question, and thanks for putting this out there.

**Comment by arcadesdude** [comment]
Strange I've use BRU on many Win11 21H1/H2 machines and haven't seen this before. My best guess is possible corruption of the msi programs list when it does:

Get-CIMInstance -class Win32_Product

I've seen some computers get stuck there because of MSI being corrupt. Could be file system corruption or a hardware issue. 

You might want to test out that computer that got hung up on that point and see if it is having any other issues.
​
