### ISSUE TITLE
Dell Optimizer Core uninstall fails with /S switch but works without

### ISSUE THREAD

**Issue by mmangelsdorf** [arcadesdude/BRU#26]
I just used the wonderful BRU to remove (almost) all Dell utilities from my machine and the only uninstall that didn't work out of the box was the one of `Dell Optimizer Core`. The setup started but then showed the following error message

![Error removing dell optimizer core](https://user-images.githubusercontent.com/13134791/228276393-27c1a95f-d39b-47b3-9360-0d8dfe587582.png)

and produced the following log entry

```
Dell Optimizer Core is being removed. (non-msi)
Running:
"C:\Program Files (x86)\InstallShield Installation Information\{286A9ADE-A581-43E8-AA85-6F5D58C7DC88}\DellOptimizer.exe" /S -remove -runfromtemp
WARNING: ExitCode: -2147219701 Dell Optimizer Core might not have been removed. Check Programs list if uninstalled. If not reboot and try again or manually uninstall. Some applications give exit codes on uninstallation but still uninstall just fine.
```

After a reboot, I tried around with the arguments and found that the following variation works (just omitting `/S`)

```
"C:\Program Files (x86)\InstallShield Installation Information\{286A9ADE-A581-43E8-AA85-6F5D58C7DC88}\DellOptimizer.exe" -remove -runfromtemp
```

Of course, this meant I had to manually click through the uninstall process.  
Unfortunately, I only later saw that `-silent` might have worked instead, but I did not try that (and don't really want to re-install that cr**ware 🙈.

**Comment by arcadesdude** [comment]
Thanks. I've merged wcg-jrogers fix for this which should address the issue.

https://github.com/arcadesdude/BRU/commit/615c8382f84e7b50d5b3f4ff2b0e4b859da9d931
