### ISSUE TITLE
On Windows 11 the Bloatware-Removal-Utility.bat doesnt start/open when running as administratror.

### ISSUE THREAD

**Issue by Chummpp** [arcadesdude/BRU#27]
Clicking on the BRU gui .bat as admin doesn't do anything. It also doesn't work when placing the streams.exe in the BRU-uninstall-helpers folder.

**Comment by arcadesdude** [comment]
You right clicked then run as admin right? Not just clicked on it when logged in as admin?

It is probably your antivirus stopping it. If there are any logs at c:\BRU can you attach them here?

**Comment by Chummpp** [comment]
> If there are any logs at c:\BRU can you attach them here?

File explorer says windows can't find C:\BRU.

**Comment by arcadesdude** [comment]
If no logs that means it didn't run so your antivirus probably killed it prior to running. HP wolf security does this sometimes. What AV was on that machine?

**Comment by arcadesdude** [comment]
closing due to no response
