### ISSUE TITLE
Causing longterm 100% CPU Usage/ unable to restore to restorepoints / overheating 

### ISSUE THREAD

**Issue by Fimxii** [arcadesdude/BRU#29]
When using BRU on new computers it seems to be causing system problems where applications start taking up 100% of the CPU power (i.e: Task Manager, Windows Desktop Services, etc). When restoring these computers to the created restorepoint or the one made before the applications it causes an automatic repair and cannot restore properly. When resetting the computer back to factory settings via usb the same problem occurs. This has happened to 2/3 of the computers this has been used on.
Any suggestions on how to revert these issues/how to avoid them in the future? 
Please note the cpu issues have occurred on both an HP and a surface pro, and we believe its messing up system files/drivers as we are getting **Stop Code: 0xc000021a**

Please let me know what you think! I am unsure as how i can fix these computers at the moment as no fixes seem to work.

Thanks,
 Fimxi

**Comment by arcadesdude** [comment]
Haven't heard of that before. Do you have logs you can share?

**Comment by Fimxii** [comment]
Of course! Although as the other logs are on a computer which is stuck in a bsodloop, i can only give you the logs from the pc which worked. But we used the same settings for each computer so this should be the same if not very similar. 

[Bloatware-Removal-22-Jun-2023-10-02.log](https://github.com/arcadesdude/BRU/files/11850236/Bloatware-Removal-22-Jun-2023-10-02.log)

**Comment by arcadesdude** [comment]
Thanks for the log. Something funny is showing at the begining with the icon not being valid. I think the ps1 file you have may be corrupt or have an invalid character encoding. Can you redownload the ps1 file from here? Then try it again on one of the affected machines? And send the new log here please.

https://github.com/arcadesdude/BRU/blob/dev/Bloatware-Removal-Utility.ps1

**Comment by arcadesdude** [comment]
Fimxii, any update on redownloading it and getting new logs?

**Comment by Fimxii** [comment]
We have fix our issue and believe that somehow our corrupt version of the software also corrupted our flash drive. Whatever computer the flashdrive was plugged into it would automatically make the CPU run at full 100%. The only way to fix the problem was to fully wipe the computer. We have no idea what fully caused this but we are not bothered enough to pursue it further! I apologize for keeping you waiting as ive been away. 

Summary: Something somehow corrupted the flash drive it was on to where if you even attached it into a computer for a second it would break the CPU. (or Moreso make the machine think it was running at full power). As the flash drive wasn't being used for anything else I have to assume it was caused by something going wrong when adding the script onto the drive. No idea though super weird glitch.
