### ISSUE TITLE
Silent execution

### ISSUE THREAD

**Issue by gully300** [arcadesdude/BRU#3]
This tool is amazing, any idea when "command line switches to run script silently again with default options" will be implemented? I see there is a globalSettingsSetIndividualVariables function and dont know if that could be leveraged.

The script I have saves variables to an xml then checks for that xml when it executes (after a restart) and resumes its setup.

**Comment by arcadesdude** [comment]
I have a plan to update this as it has been a while. There's the never ending amount of W10 bloatware to list and I want to work on an auto update feature to have the app update itself. So no specific time frame for the silent feature but it would be one of the next items for the next release.

**Comment by arcadesdude** [comment]
Gully300, Dev branch has working silent command line options. Will be merged into master and released as new version if it tests out good. You can check it out now if interested. Thanks,

**Comment by arcadesdude** [comment]
Released new version with this option implemented.
