### ISSUE TITLE
HP Client Security manager issue

### ISSUE THREAD

**Issue by onlinegill** [arcadesdude/BRU#4]
HP Client Security manager cant be uninstalled due to following apps needs to be removed first.
HP Sure Recover
HP Sure Run
Hp Sure Run

**Comment by arcadesdude** [comment]
Hi Gillz,

Could you send me the logs and I'll look into fixing that? It might be as
easy as adding those programs to the default list prior to HP Client
Security Manager.

Thanks
-arcadesdude

**Comment by onlinegill** [comment]
[Bloatware-Removal-19-Sep-2019-16-04.log]
Hi, even i removed both programs  still client security does not get removed.

**Comment by arcadesdude** [comment]
Do you have the first log? Error 1618 from MSI uninstalls usually happens
when there is another MSI uninstall already running and it hung for
whatever reason. The log you sent shows all the MSI uninstalls failed due
to that so I suspect that is a log that was 2nd run of the program. Did you
reboot before running the BRU script?

Second issue I see is you are missing the uninstall helper needed for HP
Client Security. Follow the link in the log to get that or the instructions
on the GitHub page as not having that can make HP Client Security hang
during uninstall. That might be what happening here. Devcon is the helper
what you need. (You're also missing the office uninstaller script but that
won't affect HP Client Security). Get the 64 bit version and rename it to
devcon_x64.exe

Once you have devcon in the helpers directory and reboot, try to run BRU
again and send a new log please.
