### ISSUE TITLE
HP Dock Audio

### ISSUE THREAD

**Issue by sirjoe13** [arcadesdude/BRU#7]
Hi

I cannot exclude the App "HP Dock Audio". Do you know why?

Regards,
Sergio

**Comment by arcadesdude** [comment]
Post log so I can see what's going on please. They're in C:\BRU by default. 
Thanks!

**Comment by sirjoe13** [comment]
Here the Log:

[Bloatware-Removal-26-Jun-2020-11-25.log](https://github.com/arcadesdude/BRU/files/4836816/Bloatware-Removal-26-Jun-2020-11-25.log)

**Comment by arcadesdude** [comment]
Thanks for the log. You can put quotes around items that have spaces in them so they will be excluded properly. This way of doing it with | separators between items may work better too:


powershell.exe -noprofile -executionpolicy bypass -file .\Bloatware-Removal-Utility.ps1 -s -exclude "keyboard|driver|HP Universal Camera Driver|HP Hotkey Support|HP Wireless Button Driver|HP Dock Audio" -includelast "HP Client Security Manager|HP Support Assistant" -norestorepoint -rebootafterremoval

**Comment by sirjoe13** [comment]
i've tried it. The exclusion is not working. it wants to uninstall the HP Dock Audio. :(

**Comment by arcadesdude** [comment]
Ok I'll look into it and try to repeat the issue.

**Comment by sirjoe13** [comment]
Thank you for the support 👍

**Comment by arcadesdude** [comment]
No problem. Still working on it. I was able to replicate the issue and
working on a fix. How the regex escaping is done and how it does the
matching will have to change to fix it. May be a few days.

**Comment by sirjoe13** [comment]
any news? :)

**Comment by arcadesdude** [comment]
Still working on it. I know what I need to do now and will rewrite the match code. Holiday and family visiting delayed me a bit.

**Comment by sirjoe13** [comment]
Perfect :) i was just curious if you found a solution. Enjoy your Holidays :D

**Comment by arcadesdude** [comment]
Just a quick update on the progress of this fix: I'm rewriting the core matching code and making it easier to maintain/make changes. This is taking a while and I've got lots of testing to work out. When it is ready it should resolve the inconsistencies and fix unknown bugs with the cli include options.

**Comment by arcadesdude** [comment]
I've pushed an updated version with fixes. Please let me know if you still have issues.

https://github.com/arcadesdude/BRU/releases/tag/09-20-2020
