### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by TheSteemer** [arcadesdude/BRU#8]
Is there any logging? This is crashing on one PC im trying to run it on, I have ran it on many others no issues. It closes after its compiled a list of apps

**Comment by arcadesdude** [comment]
There are logs. The poweshell script uses transcript logging and you can find the logs in c:\BRU directory. Please zip and attach here or upload so we can find the cause. I have seen it (and other winform and gui based Powershell scripts) crash if there is an issue with dotnet. 

Please reboot, update or reinstall latest dotnet framework and the reboot again and see if that helps. You can also edit out the script where it hides the console and then it will show everything it is doing in the console window which should help. 

What error message do you get and scan you provide a screenshot?

**Comment by arcadesdude** [comment]
Closing due to lack of response.
