### ISSUE TITLE
creating custom output script for repeated use

### ISSUE THREAD

**Issue by divadiow** [arcadesdude/BRU#9]
Hi.

How can I create an output based on the list of apps to then save as slim version of the routine that can be run repeatedly on different machines?

**Comment by arcadesdude** [comment]
You can just edit the bat file with what you want to remove and save that.
Look at the existing bat file and where it launches Powershell after that
are the command line arguments. There you can specify what should be
removed. Check out
https://github.com/arcadesdude/BRU#silent--command-line-usage

**Comment by divadiow** [comment]
hey cheers. yep. I was being dumb.

I'm trying to automate a silent install using a deployment tool (PDQ Deploy) and cannot get it to elevate itself to run as administrator. The returns are all about elevation. The service account used to deploy is a local administrator

**Comment by arcadesdude** [comment]
Did you get it to elevate?

I know there is a way to have a Powershell script elevate itself as long as user it is running as is local admin.
